// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyyfxqcahpzwcmersywg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5eWZ4cWNhaHB6d2NtZXJzeXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzM4MzQsImV4cCI6MjA2MjkwOTgzNH0.sZCGiOBUO0LheZChg7fESR74aF_IuVV1k3hdQm-kN9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);